#pragma once

namespace DirectX
{
	namespace D3D12
	{
		public enum class D3D12_VARIABLE_SHADING_RATE_TIER
		{
			D3D12_VARIABLE_SHADING_RATE_TIER_NOT_SUPPORTED = 0,
			D3D12_VARIABLE_SHADING_RATE_TIER_1 = 1,
			D3D12_VARIABLE_SHADING_RATE_TIER_2 = 2
		};
	}
}