#pragma once

namespace DirectX
{
    namespace D3D12
    {
        public enum class D3D12_STATE_OBJECT_FLAGS
        {
            D3D12_STATE_OBJECT_FLAG_NONE = 0,
            D3D12_STATE_OBJECT_FLAG_ALLOW_LOCAL_DEPENDENCIES_ON_EXTERNAL_DEFINITIONS = 0x1,
            D3D12_STATE_OBJECT_FLAG_ALLOW_EXTERNAL_DEPENDENCIES_ON_LOCAL_DEFINITIONS = 0x2,
            D3D12_STATE_OBJECT_FLAG_ALLOW_STATE_OBJECT_ADDITIONS = 0x4
        };
    }
}