#pragma once

#include "DXGI_ADAPTER_DESC.h"
#include "DXGI_COLOR_SPACE_TYPE.h"
#include "DXGI_FORMAT.h"
#include "DXGI_FRAME_STATISTICS.h"
#include "DXGI_GAMMA_CONTROL.h"
#include "DXGI_GAMMA_CONTROL_CAPABILITIES.h"
#include "DXGI_JPEG_AC_HUFFMAN_TABLE.h"
#include "DXGI_JPEG_DC_HUFFMAN_TABLE.h"
#include "DXGI_JPEG_QUANTIZATION_TABLE.h"
#include "DXGI_MAPPED_RECT.h"
#include "DXGI_Message_Id.h"
#include "DXGI_MODE_DESC.h"
#include "DXGI_MODE_ROTATION.h"
#include "DXGI_MODE_SCALING.h"
#include "DXGI_MODE_SCANLINE_ORDER.h"
#include "DXGI_OUTPUT_DESC.h"
#include "DXGI_RATIONAL.h"
#include "DXGI_RESIDENCY.h"
#include "DXGI_RGB.h"
#include "DXGI_RGBA.h"
#include "DXGI_SAMPLE_DESC.h"
#include "DXGI_SHARED_RESOURCE.h"
#include "DXGI_SURFACE_DESC.h"
#include "DXGI_SWAP_CHAIN_DESC.h"
#include "DXGI_SWAP_CHAIN_FLAG.h"
#include "DXGI_SWAP_EFFECT.h"
#include "DXGI_ADAPTER_FLAG.h"
#include "DXGI_ADAPTER_DESC1.h"
#include "DXGI_DISPLAY_COLOR_SPACE.h"
#include "DXGI_OUTDUPL_MOVE_RECT.h"
#include "DXGI_OUTDUPL_DESC.h"
#include "DXGI_OUTDUPL_POINTER_POSITION.h"
#include "DXGI_OUTDUPL_POINTER_SHAPE_TYPE.h"
#include "DXGI_OUTDUPL_POINTER_SHAPE_INFO.h"
#include "DXGI_ALPHA_MODE.h"
#include "DXGI_MODE_DESC1.h"
#include "DXGI_SCALING.h"
#include "DXGI_SWAP_CHAIN_DESC1.h"
#include "DXGI_SWAP_CHAIN_FULLSCREEN_DESC.h"
#include "DXGI_PRESENT_PARAMETERS.h"
#include "DXGI_GRAPHICS_PREEMPTION_GRANULARITY.h"
#include "DXGI_COMPUTE_PREEMPTION_GRANULARITY.h"
#include "DXGI_ADAPTER_DESC2.h"

#include "Debug_classes/DXGI_DEBUG_RLO_FLAGS.h"


using namespace System;

