#pragma once

using namespace System;

#undef	D3D12_16BIT_INDEX_STRIP_CUT_VALUE	
#undef	D3D12_32BIT_INDEX_STRIP_CUT_VALUE	
#undef	D3D12_8BIT_INDEX_STRIP_CUT_VALUE	
#undef	D3D12_APPEND_ALIGNED_ELEMENT	
#undef	D3D12_ARRAY_AXIS_ADDRESS_RANGE_BIT_COUNT	
#undef	D3D12_CLIP_OR_CULL_DISTANCE_COUNT	
#undef	D3D12_CLIP_OR_CULL_DISTANCE_ELEMENT_COUNT	
#undef	D3D12_COMMONSHADER_CONSTANT_BUFFER_API_SLOT_COUNT	
#undef	D3D12_COMMONSHADER_CONSTANT_BUFFER_COMPONENTS	
#undef	D3D12_COMMONSHADER_CONSTANT_BUFFER_COMPONENT_BIT_COUNT	
#undef	D3D12_COMMONSHADER_CONSTANT_BUFFER_HW_SLOT_COUNT	
#undef	D3D12_COMMONSHADER_CONSTANT_BUFFER_PARTIAL_UPDATE_EXTENTS_BYTE_ALIGNMENT	
#undef	D3D12_COMMONSHADER_CONSTANT_BUFFER_REGISTER_COMPONENTS	
#undef	D3D12_COMMONSHADER_CONSTANT_BUFFER_REGISTER_COUNT	
#undef	D3D12_COMMONSHADER_CONSTANT_BUFFER_REGISTER_READS_PER_INST	
#undef	D3D12_COMMONSHADER_CONSTANT_BUFFER_REGISTER_READ_PORTS	
#undef	D3D12_COMMONSHADER_FLOWCONTROL_NESTING_LIMIT	
#undef	D3D12_COMMONSHADER_IMMEDIATE_CONSTANT_BUFFER_REGISTER_COMPONENTS	
#undef	D3D12_COMMONSHADER_IMMEDIATE_CONSTANT_BUFFER_REGISTER_COUNT	
#undef	D3D12_COMMONSHADER_IMMEDIATE_CONSTANT_BUFFER_REGISTER_READS_PER_INST	
#undef	D3D12_COMMONSHADER_IMMEDIATE_CONSTANT_BUFFER_REGISTER_READ_PORTS	
#undef	D3D12_COMMONSHADER_IMMEDIATE_VALUE_COMPONENT_BIT_COUNT	
#undef	D3D12_COMMONSHADER_INPUT_RESOURCE_REGISTER_COMPONENTS	
#undef	D3D12_COMMONSHADER_INPUT_RESOURCE_REGISTER_COUNT	
#undef	D3D12_COMMONSHADER_INPUT_RESOURCE_REGISTER_READS_PER_INST	
#undef	D3D12_COMMONSHADER_INPUT_RESOURCE_REGISTER_READ_PORTS	
#undef	D3D12_COMMONSHADER_INPUT_RESOURCE_SLOT_COUNT	
#undef	D3D12_COMMONSHADER_SAMPLER_REGISTER_COMPONENTS	
#undef	D3D12_COMMONSHADER_SAMPLER_REGISTER_COUNT	
#undef	D3D12_COMMONSHADER_SAMPLER_REGISTER_READS_PER_INST	
#undef	D3D12_COMMONSHADER_SAMPLER_REGISTER_READ_PORTS	
#undef	D3D12_COMMONSHADER_SAMPLER_SLOT_COUNT	
#undef	D3D12_COMMONSHADER_SUBROUTINE_NESTING_LIMIT	
#undef	D3D12_COMMONSHADER_TEMP_REGISTER_COMPONENTS	
#undef	D3D12_COMMONSHADER_TEMP_REGISTER_COMPONENT_BIT_COUNT	
#undef	D3D12_COMMONSHADER_TEMP_REGISTER_COUNT	
#undef	D3D12_COMMONSHADER_TEMP_REGISTER_READS_PER_INST	
#undef	D3D12_COMMONSHADER_TEMP_REGISTER_READ_PORTS	
#undef	D3D12_COMMONSHADER_TEXCOORD_RANGE_REDUCTION_MAX	
#undef	D3D12_COMMONSHADER_TEXCOORD_RANGE_REDUCTION_MIN	
#undef	D3D12_COMMONSHADER_TEXEL_OFFSET_MAX_NEGATIVE	
#undef	D3D12_COMMONSHADER_TEXEL_OFFSET_MAX_POSITIVE	
#undef	D3D12_CONSTANT_BUFFER_DATA_PLACEMENT_ALIGNMENT	
#undef	D3D12_CS_4_X_BUCKET00_MAX_BYTES_TGSM_WRITABLE_PER_THREAD	
#undef	D3D12_CS_4_X_BUCKET00_MAX_NUM_THREADS_PER_GROUP	
#undef	D3D12_CS_4_X_BUCKET01_MAX_BYTES_TGSM_WRITABLE_PER_THREAD	
#undef	D3D12_CS_4_X_BUCKET01_MAX_NUM_THREADS_PER_GROUP	
#undef	D3D12_CS_4_X_BUCKET02_MAX_BYTES_TGSM_WRITABLE_PER_THREAD	
#undef	D3D12_CS_4_X_BUCKET02_MAX_NUM_THREADS_PER_GROUP	
#undef	D3D12_CS_4_X_BUCKET03_MAX_BYTES_TGSM_WRITABLE_PER_THREAD	
#undef	D3D12_CS_4_X_BUCKET03_MAX_NUM_THREADS_PER_GROUP	
#undef	D3D12_CS_4_X_BUCKET04_MAX_BYTES_TGSM_WRITABLE_PER_THREAD	
#undef	D3D12_CS_4_X_BUCKET04_MAX_NUM_THREADS_PER_GROUP	
#undef	D3D12_CS_4_X_BUCKET05_MAX_BYTES_TGSM_WRITABLE_PER_THREAD	
#undef	D3D12_CS_4_X_BUCKET05_MAX_NUM_THREADS_PER_GROUP	
#undef	D3D12_CS_4_X_BUCKET06_MAX_BYTES_TGSM_WRITABLE_PER_THREAD	
#undef	D3D12_CS_4_X_BUCKET06_MAX_NUM_THREADS_PER_GROUP	
#undef	D3D12_CS_4_X_BUCKET07_MAX_BYTES_TGSM_WRITABLE_PER_THREAD	
#undef	D3D12_CS_4_X_BUCKET07_MAX_NUM_THREADS_PER_GROUP	
#undef	D3D12_CS_4_X_BUCKET08_MAX_BYTES_TGSM_WRITABLE_PER_THREAD	
#undef	D3D12_CS_4_X_BUCKET08_MAX_NUM_THREADS_PER_GROUP	
#undef	D3D12_CS_4_X_BUCKET09_MAX_BYTES_TGSM_WRITABLE_PER_THREAD	
#undef	D3D12_CS_4_X_BUCKET09_MAX_NUM_THREADS_PER_GROUP	
#undef	D3D12_CS_4_X_BUCKET10_MAX_BYTES_TGSM_WRITABLE_PER_THREAD	
#undef	D3D12_CS_4_X_BUCKET10_MAX_NUM_THREADS_PER_GROUP	
#undef	D3D12_CS_4_X_BUCKET11_MAX_BYTES_TGSM_WRITABLE_PER_THREAD	
#undef	D3D12_CS_4_X_BUCKET11_MAX_NUM_THREADS_PER_GROUP	
#undef	D3D12_CS_4_X_BUCKET12_MAX_BYTES_TGSM_WRITABLE_PER_THREAD	
#undef	D3D12_CS_4_X_BUCKET12_MAX_NUM_THREADS_PER_GROUP	
#undef	D3D12_CS_4_X_BUCKET13_MAX_BYTES_TGSM_WRITABLE_PER_THREAD	
#undef	D3D12_CS_4_X_BUCKET13_MAX_NUM_THREADS_PER_GROUP	
#undef	D3D12_CS_4_X_BUCKET14_MAX_BYTES_TGSM_WRITABLE_PER_THREAD	
#undef	D3D12_CS_4_X_BUCKET14_MAX_NUM_THREADS_PER_GROUP	
#undef	D3D12_CS_4_X_BUCKET15_MAX_BYTES_TGSM_WRITABLE_PER_THREAD	
#undef	D3D12_CS_4_X_BUCKET15_MAX_NUM_THREADS_PER_GROUP	
#undef	D3D12_CS_4_X_DISPATCH_MAX_THREAD_GROUPS_IN_Z_DIMENSION	
#undef	D3D12_CS_4_X_RAW_UAV_BYTE_ALIGNMENT	
#undef	D3D12_CS_4_X_THREAD_GROUP_MAX_THREADS_PER_GROUP	
#undef	D3D12_CS_4_X_THREAD_GROUP_MAX_X	
#undef	D3D12_CS_4_X_THREAD_GROUP_MAX_Y	
#undef	D3D12_CS_4_X_UAV_REGISTER_COUNT	
#undef	D3D12_CS_DISPATCH_MAX_THREAD_GROUPS_PER_DIMENSION	
#undef	D3D12_CS_TGSM_REGISTER_COUNT	
#undef	D3D12_CS_TGSM_REGISTER_READS_PER_INST	
#undef	D3D12_CS_TGSM_RESOURCE_REGISTER_COMPONENTS	
#undef	D3D12_CS_TGSM_RESOURCE_REGISTER_READ_PORTS	
#undef	D3D12_CS_THREADGROUPID_REGISTER_COMPONENTS	
#undef	D3D12_CS_THREADGROUPID_REGISTER_COUNT	
#undef	D3D12_CS_THREADIDINGROUPFLATTENED_REGISTER_COMPONENTS	
#undef	D3D12_CS_THREADIDINGROUPFLATTENED_REGISTER_COUNT	
#undef	D3D12_CS_THREADIDINGROUP_REGISTER_COMPONENTS	
#undef	D3D12_CS_THREADIDINGROUP_REGISTER_COUNT	
#undef	D3D12_CS_THREADID_REGISTER_COMPONENTS	
#undef	D3D12_CS_THREADID_REGISTER_COUNT	
#undef	D3D12_CS_THREAD_GROUP_MAX_THREADS_PER_GROUP	
#undef	D3D12_CS_THREAD_GROUP_MAX_X	
#undef	D3D12_CS_THREAD_GROUP_MAX_Y	
#undef	D3D12_CS_THREAD_GROUP_MAX_Z	
#undef	D3D12_CS_THREAD_GROUP_MIN_X	
#undef	D3D12_CS_THREAD_GROUP_MIN_Y	
#undef	D3D12_CS_THREAD_GROUP_MIN_Z	
#undef	D3D12_CS_THREAD_LOCAL_TEMP_REGISTER_POOL	
#undef D3D12_DEFAULT_BLEND_FACTOR_ALPHA	
#undef D3D12_DEFAULT_BLEND_FACTOR_BLUE	
#undef D3D12_DEFAULT_BLEND_FACTOR_GREEN	
#undef D3D12_DEFAULT_BLEND_FACTOR_RED	
#undef D3D12_DEFAULT_BORDER_COLOR_COMPONENT	
#undef	D3D12_DEFAULT_DEPTH_BIAS	
#undef D3D12_DEFAULT_DEPTH_BIAS_CLAMP	
#undef	D3D12_DEFAULT_MAX_ANISOTROPY	
#undef D3D12_DEFAULT_MIP_LOD_BIAS	
#undef	D3D12_DEFAULT_MSAA_RESOURCE_PLACEMENT_ALIGNMENT	
#undef	D3D12_DEFAULT_RENDER_TARGET_ARRAY_INDEX	
#undef	D3D12_DEFAULT_RESOURCE_PLACEMENT_ALIGNMENT	
#undef	D3D12_DEFAULT_SAMPLE_MASK	
#undef	D3D12_DEFAULT_SCISSOR_ENDX	
#undef	D3D12_DEFAULT_SCISSOR_ENDY	
#undef	D3D12_DEFAULT_SCISSOR_STARTX	
#undef	D3D12_DEFAULT_SCISSOR_STARTY	
#undef D3D12_DEFAULT_SLOPE_SCALED_DEPTH_BIAS	
#undef	D3D12_DEFAULT_STENCIL_READ_MASK	
#undef	D3D12_DEFAULT_STENCIL_REFERENCE	
#undef	D3D12_DEFAULT_STENCIL_WRITE_MASK	
#undef	D3D12_DEFAULT_VIEWPORT_AND_SCISSORRECT_INDEX	
#undef	D3D12_DEFAULT_VIEWPORT_HEIGHT	
#undef D3D12_DEFAULT_VIEWPORT_MAX_DEPTH	
#undef D3D12_DEFAULT_VIEWPORT_MIN_DEPTH	
#undef	D3D12_DEFAULT_VIEWPORT_TOPLEFTX	
#undef	D3D12_DEFAULT_VIEWPORT_TOPLEFTY	
#undef	D3D12_DEFAULT_VIEWPORT_WIDTH	
#undef	D3D12_DESCRIPTOR_RANGE_OFFSET_APPEND	
#undef	D3D12_DRIVER_RESERVED_REGISTER_SPACE_VALUES_END	
#undef	D3D12_DRIVER_RESERVED_REGISTER_SPACE_VALUES_START	
#undef	D3D12_DS_INPUT_CONTROL_POINTS_MAX_TOTAL_SCALARS	
#undef	D3D12_DS_INPUT_CONTROL_POINT_REGISTER_COMPONENTS	
#undef	D3D12_DS_INPUT_CONTROL_POINT_REGISTER_COMPONENT_BIT_COUNT	
#undef	D3D12_DS_INPUT_CONTROL_POINT_REGISTER_COUNT	
#undef	D3D12_DS_INPUT_CONTROL_POINT_REGISTER_READS_PER_INST	
#undef	D3D12_DS_INPUT_CONTROL_POINT_REGISTER_READ_PORTS	
#undef	D3D12_DS_INPUT_DOMAIN_POINT_REGISTER_COMPONENTS	
#undef	D3D12_DS_INPUT_DOMAIN_POINT_REGISTER_COMPONENT_BIT_COUNT	
#undef	D3D12_DS_INPUT_DOMAIN_POINT_REGISTER_COUNT	
#undef	D3D12_DS_INPUT_DOMAIN_POINT_REGISTER_READS_PER_INST	
#undef	D3D12_DS_INPUT_DOMAIN_POINT_REGISTER_READ_PORTS	
#undef	D3D12_DS_INPUT_PATCH_CONSTANT_REGISTER_COMPONENTS	
#undef	D3D12_DS_INPUT_PATCH_CONSTANT_REGISTER_COMPONENT_BIT_COUNT	
#undef	D3D12_DS_INPUT_PATCH_CONSTANT_REGISTER_COUNT	
#undef	D3D12_DS_INPUT_PATCH_CONSTANT_REGISTER_READS_PER_INST	
#undef	D3D12_DS_INPUT_PATCH_CONSTANT_REGISTER_READ_PORTS	
#undef	D3D12_DS_INPUT_PRIMITIVE_ID_REGISTER_COMPONENTS	
#undef	D3D12_DS_INPUT_PRIMITIVE_ID_REGISTER_COMPONENT_BIT_COUNT	
#undef	D3D12_DS_INPUT_PRIMITIVE_ID_REGISTER_COUNT	
#undef	D3D12_DS_INPUT_PRIMITIVE_ID_REGISTER_READS_PER_INST	
#undef	D3D12_DS_INPUT_PRIMITIVE_ID_REGISTER_READ_PORTS	
#undef	D3D12_DS_OUTPUT_REGISTER_COMPONENTS	
#undef	D3D12_DS_OUTPUT_REGISTER_COMPONENT_BIT_COUNT	
#undef	D3D12_DS_OUTPUT_REGISTER_COUNT	
#undef D3D12_FLOAT16_FUSED_TOLERANCE_IN_ULP	
#undef D3D12_FLOAT32_MAX	
#undef D3D12_FLOAT32_TO_INTEGER_TOLERANCE_IN_ULP	
#undef D3D12_FLOAT_TO_SRGB_EXPONENT_DENOMINATOR	
#undef D3D12_FLOAT_TO_SRGB_EXPONENT_NUMERATOR	
#undef D3D12_FLOAT_TO_SRGB_OFFSET	
#undef D3D12_FLOAT_TO_SRGB_SCALE_1	
#undef D3D12_FLOAT_TO_SRGB_SCALE_2	
#undef D3D12_FLOAT_TO_SRGB_THRESHOLD	
#undef D3D12_FTOI_INSTRUCTION_MAX_INPUT	
#undef D3D12_FTOI_INSTRUCTION_MIN_INPUT	
#undef D3D12_FTOU_INSTRUCTION_MAX_INPUT	
#undef D3D12_FTOU_INSTRUCTION_MIN_INPUT	
#undef	D3D12_GS_INPUT_INSTANCE_ID_READS_PER_INST	
#undef	D3D12_GS_INPUT_INSTANCE_ID_READ_PORTS	
#undef	D3D12_GS_INPUT_INSTANCE_ID_REGISTER_COMPONENTS	
#undef	D3D12_GS_INPUT_INSTANCE_ID_REGISTER_COMPONENT_BIT_COUNT	
#undef	D3D12_GS_INPUT_INSTANCE_ID_REGISTER_COUNT	
#undef	D3D12_GS_INPUT_PRIM_CONST_REGISTER_COMPONENTS	
#undef	D3D12_GS_INPUT_PRIM_CONST_REGISTER_COMPONENT_BIT_COUNT	
#undef	D3D12_GS_INPUT_PRIM_CONST_REGISTER_COUNT	
#undef	D3D12_GS_INPUT_PRIM_CONST_REGISTER_READS_PER_INST	
#undef	D3D12_GS_INPUT_PRIM_CONST_REGISTER_READ_PORTS	
#undef	D3D12_GS_INPUT_REGISTER_COMPONENTS	
#undef	D3D12_GS_INPUT_REGISTER_COMPONENT_BIT_COUNT	
#undef	D3D12_GS_INPUT_REGISTER_COUNT	
#undef	D3D12_GS_INPUT_REGISTER_READS_PER_INST	
#undef	D3D12_GS_INPUT_REGISTER_READ_PORTS	
#undef	D3D12_GS_INPUT_REGISTER_VERTICES	
#undef	D3D12_GS_MAX_INSTANCE_COUNT	
#undef	D3D12_GS_MAX_OUTPUT_VERTEX_COUNT_ACROSS_INSTANCES	
#undef	D3D12_GS_OUTPUT_ELEMENTS	
#undef	D3D12_GS_OUTPUT_REGISTER_COMPONENTS	
#undef	D3D12_GS_OUTPUT_REGISTER_COMPONENT_BIT_COUNT	
#undef	D3D12_GS_OUTPUT_REGISTER_COUNT	
#undef	D3D12_HS_CONTROL_POINT_PHASE_INPUT_REGISTER_COUNT	
#undef	D3D12_HS_CONTROL_POINT_PHASE_OUTPUT_REGISTER_COUNT	
#undef	D3D12_HS_CONTROL_POINT_REGISTER_COMPONENTS	
#undef	D3D12_HS_CONTROL_POINT_REGISTER_COMPONENT_BIT_COUNT	
#undef	D3D12_HS_CONTROL_POINT_REGISTER_READS_PER_INST	
#undef	D3D12_HS_CONTROL_POINT_REGISTER_READ_PORTS	
#undef	D3D12_HS_FORK_PHASE_INSTANCE_COUNT_UPPER_BOUND	
#undef	D3D12_HS_INPUT_FORK_INSTANCE_ID_REGISTER_COMPONENTS	
#undef	D3D12_HS_INPUT_FORK_INSTANCE_ID_REGISTER_COMPONENT_BIT_COUNT	
#undef	D3D12_HS_INPUT_FORK_INSTANCE_ID_REGISTER_COUNT	
#undef	D3D12_HS_INPUT_FORK_INSTANCE_ID_REGISTER_READS_PER_INST	
#undef	D3D12_HS_INPUT_FORK_INSTANCE_ID_REGISTER_READ_PORTS	
#undef	D3D12_HS_INPUT_JOIN_INSTANCE_ID_REGISTER_COMPONENTS	
#undef	D3D12_HS_INPUT_JOIN_INSTANCE_ID_REGISTER_COMPONENT_BIT_COUNT	
#undef	D3D12_HS_INPUT_JOIN_INSTANCE_ID_REGISTER_COUNT	
#undef	D3D12_HS_INPUT_JOIN_INSTANCE_ID_REGISTER_READS_PER_INST	
#undef	D3D12_HS_INPUT_JOIN_INSTANCE_ID_REGISTER_READ_PORTS	
#undef	D3D12_HS_INPUT_PRIMITIVE_ID_REGISTER_COMPONENTS	
#undef	D3D12_HS_INPUT_PRIMITIVE_ID_REGISTER_COMPONENT_BIT_COUNT	
#undef	D3D12_HS_INPUT_PRIMITIVE_ID_REGISTER_COUNT	
#undef	D3D12_HS_INPUT_PRIMITIVE_ID_REGISTER_READS_PER_INST	
#undef	D3D12_HS_INPUT_PRIMITIVE_ID_REGISTER_READ_PORTS	
#undef	D3D12_HS_JOIN_PHASE_INSTANCE_COUNT_UPPER_BOUND	
#undef D3D12_HS_MAXTESSFACTOR_LOWER_BOUND	
#undef D3D12_HS_MAXTESSFACTOR_UPPER_BOUND	
#undef	D3D12_HS_OUTPUT_CONTROL_POINTS_MAX_TOTAL_SCALARS	
#undef	D3D12_HS_OUTPUT_CONTROL_POINT_ID_REGISTER_COMPONENTS	
#undef	D3D12_HS_OUTPUT_CONTROL_POINT_ID_REGISTER_COMPONENT_BIT_COUNT	
#undef	D3D12_HS_OUTPUT_CONTROL_POINT_ID_REGISTER_COUNT	
#undef	D3D12_HS_OUTPUT_CONTROL_POINT_ID_REGISTER_READS_PER_INST	
#undef	D3D12_HS_OUTPUT_CONTROL_POINT_ID_REGISTER_READ_PORTS	
#undef	D3D12_HS_OUTPUT_PATCH_CONSTANT_REGISTER_COMPONENTS	
#undef	D3D12_HS_OUTPUT_PATCH_CONSTANT_REGISTER_COMPONENT_BIT_COUNT	
#undef	D3D12_HS_OUTPUT_PATCH_CONSTANT_REGISTER_COUNT	
#undef	D3D12_HS_OUTPUT_PATCH_CONSTANT_REGISTER_READS_PER_INST	
#undef	D3D12_HS_OUTPUT_PATCH_CONSTANT_REGISTER_READ_PORTS	
#undef	D3D12_HS_OUTPUT_PATCH_CONSTANT_REGISTER_SCALAR_COMPONENTS	
#undef	D3D12_IA_DEFAULT_INDEX_BUFFER_OFFSET_IN_BYTES	
#undef	D3D12_IA_DEFAULT_PRIMITIVE_TOPOLOGY	
#undef	D3D12_IA_DEFAULT_VERTEX_BUFFER_OFFSET_IN_BYTES	
#undef	D3D12_IA_INDEX_INPUT_RESOURCE_SLOT_COUNT	
#undef	D3D12_IA_INSTANCE_ID_BIT_COUNT	
#undef	D3D12_IA_INTEGER_ARITHMETIC_BIT_COUNT	
#undef	D3D12_IA_PATCH_MAX_CONTROL_POINT_COUNT	
#undef	D3D12_IA_PRIMITIVE_ID_BIT_COUNT	
#undef	D3D12_IA_VERTEX_ID_BIT_COUNT	
#undef	D3D12_IA_VERTEX_INPUT_RESOURCE_SLOT_COUNT	
#undef	D3D12_IA_VERTEX_INPUT_STRUCTURE_ELEMENTS_COMPONENTS	
#undef	D3D12_IA_VERTEX_INPUT_STRUCTURE_ELEMENT_COUNT	
#undef	D3D12_INTEGER_DIVIDE_BY_ZERO_QUOTIENT	
#undef	D3D12_INTEGER_DIVIDE_BY_ZERO_REMAINDER	
#undef	D3D12_KEEP_RENDER_TARGETS_AND_DEPTH_STENCIL	
#undef	D3D12_KEEP_UNORDERED_ACCESS_VIEWS	
#undef D3D12_LINEAR_GAMMA	
#undef	D3D12_MAJOR_VERSION	
#undef D3D12_MAX_BORDER_COLOR_COMPONENT	
#undef D3D12_MAX_DEPTH	
#undef	D3D12_MAX_LIVE_STATIC_SAMPLERS	
#undef	D3D12_MAX_MAXANISOTROPY	
#undef	D3D12_MAX_MULTISAMPLE_SAMPLE_COUNT	
#undef D3D12_MAX_POSITION_VALUE	
#undef	D3D12_MAX_ROOT_COST	
#undef	D3D12_MAX_SHADER_VISIBLE_DESCRIPTOR_HEAP_SIZE_TIER_1	
#undef	D3D12_MAX_SHADER_VISIBLE_DESCRIPTOR_HEAP_SIZE_TIER_2	
#undef	D3D12_MAX_SHADER_VISIBLE_SAMPLER_HEAP_SIZE	
#undef	D3D12_MAX_TEXTURE_DIMENSION_2_TO_EXP	
#undef	D3D12_MAX_VIEW_INSTANCE_COUNT	
#undef	D3D12_MINOR_VERSION	
#undef D3D12_MIN_BORDER_COLOR_COMPONENT	
#undef D3D12_MIN_DEPTH	
#undef	D3D12_MIN_MAXANISOTROPY	
#undef D3D12_MIP_LOD_BIAS_MAX	
#undef D3D12_MIP_LOD_BIAS_MIN	
#undef	D3D12_MIP_LOD_FRACTIONAL_BIT_COUNT	
#undef	D3D12_MIP_LOD_RANGE_BIT_COUNT	
#undef D3D12_MULTISAMPLE_ANTIALIAS_LINE_WIDTH	
#undef	D3D12_NONSAMPLE_FETCH_OUT_OF_RANGE_ACCESS_RESULT	
#undef	D3D12_OS_RESERVED_REGISTER_SPACE_VALUES_END	
#undef	D3D12_OS_RESERVED_REGISTER_SPACE_VALUES_START	
#undef	D3D12_PACKED_TILE	
#undef	D3D12_PIXEL_ADDRESS_RANGE_BIT_COUNT	
#undef	D3D12_PRE_SCISSOR_PIXEL_ADDRESS_RANGE_BIT_COUNT	
#undef	D3D12_PS_CS_UAV_REGISTER_COMPONENTS	
#undef	D3D12_PS_CS_UAV_REGISTER_COUNT	
#undef	D3D12_PS_CS_UAV_REGISTER_READS_PER_INST	
#undef	D3D12_PS_CS_UAV_REGISTER_READ_PORTS	
#undef	D3D12_PS_FRONTFACING_DEFAULT_VALUE	
#undef	D3D12_PS_FRONTFACING_FALSE_VALUE	
#undef	D3D12_PS_FRONTFACING_TRUE_VALUE	
#undef	D3D12_PS_INPUT_REGISTER_COMPONENTS	
#undef	D3D12_PS_INPUT_REGISTER_COMPONENT_BIT_COUNT	
#undef	D3D12_PS_INPUT_REGISTER_COUNT	
#undef	D3D12_PS_INPUT_REGISTER_READS_PER_INST	
#undef	D3D12_PS_INPUT_REGISTER_READ_PORTS	
#undef D3D12_PS_LEGACY_PIXEL_CENTER_FRACTIONAL_COMPONENT	
#undef	D3D12_PS_OUTPUT_DEPTH_REGISTER_COMPONENTS	
#undef	D3D12_PS_OUTPUT_DEPTH_REGISTER_COMPONENT_BIT_COUNT	
#undef	D3D12_PS_OUTPUT_DEPTH_REGISTER_COUNT	
#undef	D3D12_PS_OUTPUT_MASK_REGISTER_COMPONENTS	
#undef	D3D12_PS_OUTPUT_MASK_REGISTER_COMPONENT_BIT_COUNT	
#undef	D3D12_PS_OUTPUT_MASK_REGISTER_COUNT	
#undef	D3D12_PS_OUTPUT_REGISTER_COMPONENTS	
#undef	D3D12_PS_OUTPUT_REGISTER_COMPONENT_BIT_COUNT	
#undef	D3D12_PS_OUTPUT_REGISTER_COUNT	
#undef D3D12_PS_PIXEL_CENTER_FRACTIONAL_COMPONENT	
#undef	D3D12_RAW_UAV_SRV_BYTE_ALIGNMENT	
#undef	D3D12_RAYTRACING_AABB_BYTE_ALIGNMENT	
#undef	D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BYTE_ALIGNMENT	
#undef	D3D12_RAYTRACING_INSTANCE_DESCS_BYTE_ALIGNMENT	
#undef	D3D12_RAYTRACING_MAX_ATTRIBUTE_SIZE_IN_BYTES	
#undef	D3D12_RAYTRACING_MAX_DECLARABLE_TRACE_RECURSION_DEPTH	
#undef	D3D12_RAYTRACING_MAX_GEOMETRIES_PER_BOTTOM_LEVEL_ACCELERATION_STRUCTURE	
#undef	D3D12_RAYTRACING_MAX_INSTANCES_PER_TOP_LEVEL_ACCELERATION_STRUCTURE	
#undef	D3D12_RAYTRACING_MAX_PRIMITIVES_PER_BOTTOM_LEVEL_ACCELERATION_STRUCTURE	
#undef	D3D12_RAYTRACING_MAX_RAY_GENERATION_SHADER_THREADS	
#undef	D3D12_RAYTRACING_MAX_SHADER_RECORD_STRIDE	
#undef	D3D12_RAYTRACING_SHADER_RECORD_BYTE_ALIGNMENT	
#undef	D3D12_RAYTRACING_SHADER_TABLE_BYTE_ALIGNMENT	
#undef	D3D12_RAYTRACING_TRANSFORM3X4_BYTE_ALIGNMENT	
#undef	D3D12_REQ_BLEND_OBJECT_COUNT_PER_DEVICE	
#undef	D3D12_REQ_BUFFER_RESOURCE_TEXEL_COUNT_2_TO_EXP	
#undef	D3D12_REQ_CONSTANT_BUFFER_ELEMENT_COUNT	
#undef	D3D12_REQ_DEPTH_STENCIL_OBJECT_COUNT_PER_DEVICE	
#undef	D3D12_REQ_DRAWINDEXED_INDEX_COUNT_2_TO_EXP	
#undef	D3D12_REQ_DRAW_VERTEX_COUNT_2_TO_EXP	
#undef	D3D12_REQ_FILTERING_HW_ADDRESSABLE_RESOURCE_DIMENSION	
#undef	D3D12_REQ_GS_INVOCATION_32BIT_OUTPUT_COMPONENT_LIMIT	
#undef	D3D12_REQ_IMMEDIATE_CONSTANT_BUFFER_ELEMENT_COUNT	
#undef	D3D12_REQ_MAXANISOTROPY	
#undef	D3D12_REQ_MIP_LEVELS	
#undef	D3D12_REQ_MULTI_ELEMENT_STRUCTURE_SIZE_IN_BYTES	
#undef	D3D12_REQ_RASTERIZER_OBJECT_COUNT_PER_DEVICE	
#undef	D3D12_REQ_RENDER_TO_BUFFER_WINDOW_WIDTH	
#undef	D3D12_REQ_RESOURCE_SIZE_IN_MEGABYTES_EXPRESSION_A_TERM	
#undef D3D12_REQ_RESOURCE_SIZE_IN_MEGABYTES_EXPRESSION_B_TERM	
#undef	D3D12_REQ_RESOURCE_SIZE_IN_MEGABYTES_EXPRESSION_C_TERM	
#undef	D3D12_REQ_RESOURCE_VIEW_COUNT_PER_DEVICE_2_TO_EXP	
#undef	D3D12_REQ_SAMPLER_OBJECT_COUNT_PER_DEVICE	
#undef	D3D12_REQ_SUBRESOURCES	
#undef	D3D12_REQ_TEXTURE1D_ARRAY_AXIS_DIMENSION	
#undef	D3D12_REQ_TEXTURE1D_U_DIMENSION	
#undef	D3D12_REQ_TEXTURE2D_ARRAY_AXIS_DIMENSION	
#undef	D3D12_REQ_TEXTURE2D_U_OR_V_DIMENSION	
#undef	D3D12_REQ_TEXTURE3D_U_V_OR_W_DIMENSION	
#undef	D3D12_REQ_TEXTURECUBE_DIMENSION	
#undef	D3D12_RESINFO_INSTRUCTION_MISSING_COMPONENT_RETVAL	
#undef	D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES	
#undef	D3D12_RS_SET_SHADING_RATE_COMBINER_COUNT	
#undef	D3D12_SHADER_IDENTIFIER_SIZE_IN_BYTES	
#undef	D3D12_SHADER_MAJOR_VERSION	
#undef	D3D12_SHADER_MAX_INSTANCES	
#undef	D3D12_SHADER_MAX_INTERFACES	
#undef	D3D12_SHADER_MAX_INTERFACE_CALL_SITES	
#undef	D3D12_SHADER_MAX_TYPES	
#undef	D3D12_SHADER_MINOR_VERSION	
#undef	D3D12_SHIFT_INSTRUCTION_PAD_VALUE	
#undef	D3D12_SHIFT_INSTRUCTION_SHIFT_VALUE_BIT_COUNT	
#undef	D3D12_SIMULTANEOUS_RENDER_TARGET_COUNT	
#undef	D3D12_SMALL_MSAA_RESOURCE_PLACEMENT_ALIGNMENT	
#undef	D3D12_SMALL_RESOURCE_PLACEMENT_ALIGNMENT	
#undef	D3D12_SO_BUFFER_MAX_STRIDE_IN_BYTES	
#undef	D3D12_SO_BUFFER_MAX_WRITE_WINDOW_IN_BYTES	
#undef	D3D12_SO_BUFFER_SLOT_COUNT	
#undef	D3D12_SO_DDI_REGISTER_INDEX_DENOTING_GAP	
#undef	D3D12_SO_NO_RASTERIZED_STREAM	
#undef	D3D12_SO_OUTPUT_COMPONENT_COUNT	
#undef	D3D12_SO_STREAM_COUNT	
#undef	D3D12_SPEC_DATE_DAY	
#undef	D3D12_SPEC_DATE_MONTH	
#undef	D3D12_SPEC_DATE_YEAR	
#undef D3D12_SPEC_VERSION	
#undef D3D12_SRGB_GAMMA	
#undef D3D12_SRGB_TO_FLOAT_DENOMINATOR_1	
#undef D3D12_SRGB_TO_FLOAT_DENOMINATOR_2	
#undef D3D12_SRGB_TO_FLOAT_EXPONENT	
#undef D3D12_SRGB_TO_FLOAT_OFFSET	
#undef D3D12_SRGB_TO_FLOAT_THRESHOLD	
#undef D3D12_SRGB_TO_FLOAT_TOLERANCE_IN_ULP	
#undef	D3D12_STANDARD_COMPONENT_BIT_COUNT	
#undef	D3D12_STANDARD_COMPONENT_BIT_COUNT_DOUBLED	
#undef	D3D12_STANDARD_MAXIMUM_ELEMENT_ALIGNMENT_BYTE_MULTIPLE	
#undef	D3D12_STANDARD_PIXEL_COMPONENT_COUNT	
#undef	D3D12_STANDARD_PIXEL_ELEMENT_COUNT	
#undef	D3D12_STANDARD_VECTOR_SIZE	
#undef	D3D12_STANDARD_VERTEX_ELEMENT_COUNT	
#undef	D3D12_STANDARD_VERTEX_TOTAL_COMPONENT_COUNT	
#undef	D3D12_SUBPIXEL_FRACTIONAL_BIT_COUNT	
#undef	D3D12_SUBTEXEL_FRACTIONAL_BIT_COUNT	
#undef	D3D12_SYSTEM_RESERVED_REGISTER_SPACE_VALUES_END	
#undef	D3D12_SYSTEM_RESERVED_REGISTER_SPACE_VALUES_START	
#undef	D3D12_TESSELLATOR_MAX_EVEN_TESSELLATION_FACTOR	
#undef	D3D12_TESSELLATOR_MAX_ISOLINE_DENSITY_TESSELLATION_FACTOR	
#undef	D3D12_TESSELLATOR_MAX_ODD_TESSELLATION_FACTOR	
#undef	D3D12_TESSELLATOR_MAX_TESSELLATION_FACTOR	
#undef	D3D12_TESSELLATOR_MIN_EVEN_TESSELLATION_FACTOR	
#undef	D3D12_TESSELLATOR_MIN_ISOLINE_DENSITY_TESSELLATION_FACTOR	
#undef	D3D12_TESSELLATOR_MIN_ODD_TESSELLATION_FACTOR	
#undef	D3D12_TEXEL_ADDRESS_RANGE_BIT_COUNT	
#undef	D3D12_TEXTURE_DATA_PITCH_ALIGNMENT	
#undef	D3D12_TEXTURE_DATA_PLACEMENT_ALIGNMENT	
#undef	D3D12_TILED_RESOURCE_TILE_SIZE_IN_BYTES	
#undef	D3D12_TRACKED_WORKLOAD_MAX_INSTANCES	
#undef	D3D12_UAV_COUNTER_PLACEMENT_ALIGNMENT	
#undef	D3D12_UAV_SLOT_COUNT	
#undef	D3D12_UNBOUND_MEMORY_ACCESS_RESULT	
#undef	D3D12_VIDEO_DECODE_MAX_ARGUMENTS	
#undef	D3D12_VIDEO_DECODE_MAX_HISTOGRAM_COMPONENTS	
#undef	D3D12_VIDEO_DECODE_MIN_BITSTREAM_OFFSET_ALIGNMENT	
#undef	D3D12_VIDEO_DECODE_MIN_HISTOGRAM_OFFSET_ALIGNMENT	
#undef	D3D12_VIDEO_DECODE_STATUS_MACROBLOCKS_AFFECTED_UNKNOWN	
#undef	D3D12_VIDEO_PROCESS_MAX_FILTERS	
#undef	D3D12_VIDEO_PROCESS_STEREO_VIEWS	
#undef	D3D12_VIEWPORT_AND_SCISSORRECT_MAX_INDEX	
#undef	D3D12_VIEWPORT_AND_SCISSORRECT_OBJECT_COUNT_PER_PIPELINE	
#undef	D3D12_VIEWPORT_BOUNDS_MAX	
#undef	D3D12_VIEWPORT_BOUNDS_MIN	
#undef	D3D12_VS_INPUT_REGISTER_COMPONENTS	
#undef	D3D12_VS_INPUT_REGISTER_COMPONENT_BIT_COUNT	
#undef	D3D12_VS_INPUT_REGISTER_COUNT	
#undef	D3D12_VS_INPUT_REGISTER_READS_PER_INST	
#undef	D3D12_VS_INPUT_REGISTER_READ_PORTS	
#undef	D3D12_VS_OUTPUT_REGISTER_COMPONENTS	
#undef	D3D12_VS_OUTPUT_REGISTER_COMPONENT_BIT_COUNT	
#undef	D3D12_VS_OUTPUT_REGISTER_COUNT	
#undef	D3D12_WHQL_CONTEXT_COUNT_FOR_RESOURCE_LIMIT	
#undef	D3D12_WHQL_DRAWINDEXED_INDEX_COUNT_2_TO_EXP	
#undef	D3D12_WHQL_DRAW_VERTEX_COUNT_2_TO_EXP	

namespace DirectX 
{
	namespace D3D12
	{
		public ref class D3D12
		{
		public:
			static const int D3D12_16BIT_INDEX_STRIP_CUT_VALUE	= 0xffff;
			static const unsigned int	D3D12_32BIT_INDEX_STRIP_CUT_VALUE	= 0xffffffff;
			static const int	D3D12_8BIT_INDEX_STRIP_CUT_VALUE	= 0xff;
			static const unsigned int	D3D12_APPEND_ALIGNED_ELEMENT	= 0xffffffff;
			static const int	D3D12_ARRAY_AXIS_ADDRESS_RANGE_BIT_COUNT	= 9;
			static const int	D3D12_CLIP_OR_CULL_DISTANCE_COUNT	= 8;
			static const int	D3D12_CLIP_OR_CULL_DISTANCE_ELEMENT_COUNT	= 2;
			static const int	D3D12_COMMONSHADER_CONSTANT_BUFFER_API_SLOT_COUNT	= 14;
			static const int	D3D12_COMMONSHADER_CONSTANT_BUFFER_COMPONENTS	= 4;
			static const int	D3D12_COMMONSHADER_CONSTANT_BUFFER_COMPONENT_BIT_COUNT	= 32;
			static const int	D3D12_COMMONSHADER_CONSTANT_BUFFER_HW_SLOT_COUNT	= 15;
			static const int	D3D12_COMMONSHADER_CONSTANT_BUFFER_PARTIAL_UPDATE_EXTENTS_BYTE_ALIGNMENT	= 16;
			static const int	D3D12_COMMONSHADER_CONSTANT_BUFFER_REGISTER_COMPONENTS	= 4;
			static const int	D3D12_COMMONSHADER_CONSTANT_BUFFER_REGISTER_COUNT	= 15;
			static const int	D3D12_COMMONSHADER_CONSTANT_BUFFER_REGISTER_READS_PER_INST	= 1;
			static const int	D3D12_COMMONSHADER_CONSTANT_BUFFER_REGISTER_READ_PORTS	= 1;
			static const int	D3D12_COMMONSHADER_FLOWCONTROL_NESTING_LIMIT	= 64;
			static const int	D3D12_COMMONSHADER_IMMEDIATE_CONSTANT_BUFFER_REGISTER_COMPONENTS	= 4;
			static const int	D3D12_COMMONSHADER_IMMEDIATE_CONSTANT_BUFFER_REGISTER_COUNT	= 1;
			static const int	D3D12_COMMONSHADER_IMMEDIATE_CONSTANT_BUFFER_REGISTER_READS_PER_INST	= 1;
			static const int	D3D12_COMMONSHADER_IMMEDIATE_CONSTANT_BUFFER_REGISTER_READ_PORTS	= 1;
			static const int	D3D12_COMMONSHADER_IMMEDIATE_VALUE_COMPONENT_BIT_COUNT	= 32;
			static const int	D3D12_COMMONSHADER_INPUT_RESOURCE_REGISTER_COMPONENTS	= 1;
			static const int	D3D12_COMMONSHADER_INPUT_RESOURCE_REGISTER_COUNT	= 128;
			static const int	D3D12_COMMONSHADER_INPUT_RESOURCE_REGISTER_READS_PER_INST	= 1;
			static const int	D3D12_COMMONSHADER_INPUT_RESOURCE_REGISTER_READ_PORTS	= 1;
			static const int	D3D12_COMMONSHADER_INPUT_RESOURCE_SLOT_COUNT	= 128;
			static const int	D3D12_COMMONSHADER_SAMPLER_REGISTER_COMPONENTS	= 1;
			static const int	D3D12_COMMONSHADER_SAMPLER_REGISTER_COUNT	= 16;
			static const int	D3D12_COMMONSHADER_SAMPLER_REGISTER_READS_PER_INST	= 1;
			static const int	D3D12_COMMONSHADER_SAMPLER_REGISTER_READ_PORTS	= 1;
			static const int	D3D12_COMMONSHADER_SAMPLER_SLOT_COUNT	= 16;
			static const int	D3D12_COMMONSHADER_SUBROUTINE_NESTING_LIMIT	= 32;
			static const int	D3D12_COMMONSHADER_TEMP_REGISTER_COMPONENTS	= 4;
			static const int	D3D12_COMMONSHADER_TEMP_REGISTER_COMPONENT_BIT_COUNT	= 32;
			static const int	D3D12_COMMONSHADER_TEMP_REGISTER_COUNT	= 4096;
			static const int	D3D12_COMMONSHADER_TEMP_REGISTER_READS_PER_INST	= 3;
			static const int	D3D12_COMMONSHADER_TEMP_REGISTER_READ_PORTS	= 3;
			static const int	D3D12_COMMONSHADER_TEXCOORD_RANGE_REDUCTION_MAX	= 10;
			static const int	D3D12_COMMONSHADER_TEXCOORD_RANGE_REDUCTION_MIN	= -10;
			static const int	D3D12_COMMONSHADER_TEXEL_OFFSET_MAX_NEGATIVE	= -8;
			static const int	D3D12_COMMONSHADER_TEXEL_OFFSET_MAX_POSITIVE	= 7;
			static const int	D3D12_CONSTANT_BUFFER_DATA_PLACEMENT_ALIGNMENT	= 256;
			static const int	D3D12_CS_4_X_BUCKET00_MAX_BYTES_TGSM_WRITABLE_PER_THREAD	= 256;
			static const int	D3D12_CS_4_X_BUCKET00_MAX_NUM_THREADS_PER_GROUP	= 64;
			static const int	D3D12_CS_4_X_BUCKET01_MAX_BYTES_TGSM_WRITABLE_PER_THREAD	= 240;
			static const int	D3D12_CS_4_X_BUCKET01_MAX_NUM_THREADS_PER_GROUP	= 68;
			static const int	D3D12_CS_4_X_BUCKET02_MAX_BYTES_TGSM_WRITABLE_PER_THREAD	= 224;
			static const int	D3D12_CS_4_X_BUCKET02_MAX_NUM_THREADS_PER_GROUP	= 72;
			static const int	D3D12_CS_4_X_BUCKET03_MAX_BYTES_TGSM_WRITABLE_PER_THREAD	= 208;
			static const int	D3D12_CS_4_X_BUCKET03_MAX_NUM_THREADS_PER_GROUP	= 76;
			static const int	D3D12_CS_4_X_BUCKET04_MAX_BYTES_TGSM_WRITABLE_PER_THREAD	= 192;
			static const int	D3D12_CS_4_X_BUCKET04_MAX_NUM_THREADS_PER_GROUP	= 84;
			static const int	D3D12_CS_4_X_BUCKET05_MAX_BYTES_TGSM_WRITABLE_PER_THREAD	= 176;
			static const int	D3D12_CS_4_X_BUCKET05_MAX_NUM_THREADS_PER_GROUP	= 92;
			static const int	D3D12_CS_4_X_BUCKET06_MAX_BYTES_TGSM_WRITABLE_PER_THREAD	= 160;
			static const int	D3D12_CS_4_X_BUCKET06_MAX_NUM_THREADS_PER_GROUP	= 100;
			static const int	D3D12_CS_4_X_BUCKET07_MAX_BYTES_TGSM_WRITABLE_PER_THREAD	= 144;
			static const int	D3D12_CS_4_X_BUCKET07_MAX_NUM_THREADS_PER_GROUP	= 112;
			static const int	D3D12_CS_4_X_BUCKET08_MAX_BYTES_TGSM_WRITABLE_PER_THREAD	= 128;
			static const int	D3D12_CS_4_X_BUCKET08_MAX_NUM_THREADS_PER_GROUP	= 128;
			static const int	D3D12_CS_4_X_BUCKET09_MAX_BYTES_TGSM_WRITABLE_PER_THREAD	= 112;
			static const int	D3D12_CS_4_X_BUCKET09_MAX_NUM_THREADS_PER_GROUP	= 144;
			static const int	D3D12_CS_4_X_BUCKET10_MAX_BYTES_TGSM_WRITABLE_PER_THREAD	= 96;
			static const int	D3D12_CS_4_X_BUCKET10_MAX_NUM_THREADS_PER_GROUP	= 168;
			static const int	D3D12_CS_4_X_BUCKET11_MAX_BYTES_TGSM_WRITABLE_PER_THREAD	= 80;
			static const int	D3D12_CS_4_X_BUCKET11_MAX_NUM_THREADS_PER_GROUP	= 204;
			static const int	D3D12_CS_4_X_BUCKET12_MAX_BYTES_TGSM_WRITABLE_PER_THREAD	= 64;
			static const int	D3D12_CS_4_X_BUCKET12_MAX_NUM_THREADS_PER_GROUP	= 256;
			static const int	D3D12_CS_4_X_BUCKET13_MAX_BYTES_TGSM_WRITABLE_PER_THREAD	= 48;
			static const int	D3D12_CS_4_X_BUCKET13_MAX_NUM_THREADS_PER_GROUP	= 340;
			static const int	D3D12_CS_4_X_BUCKET14_MAX_BYTES_TGSM_WRITABLE_PER_THREAD	= 32;
			static const int	D3D12_CS_4_X_BUCKET14_MAX_NUM_THREADS_PER_GROUP	= 512;
			static const int	D3D12_CS_4_X_BUCKET15_MAX_BYTES_TGSM_WRITABLE_PER_THREAD	= 16;
			static const int	D3D12_CS_4_X_BUCKET15_MAX_NUM_THREADS_PER_GROUP	= 768;
			static const int	D3D12_CS_4_X_DISPATCH_MAX_THREAD_GROUPS_IN_Z_DIMENSION	= 1;
			static const int	D3D12_CS_4_X_RAW_UAV_BYTE_ALIGNMENT	= 256;
			static const int	D3D12_CS_4_X_THREAD_GROUP_MAX_THREADS_PER_GROUP	= 768;
			static const int	D3D12_CS_4_X_THREAD_GROUP_MAX_X	= 768;
			static const int	D3D12_CS_4_X_THREAD_GROUP_MAX_Y	= 768;
			static const int	D3D12_CS_4_X_UAV_REGISTER_COUNT	= 1;
			static const int	D3D12_CS_DISPATCH_MAX_THREAD_GROUPS_PER_DIMENSION	= 65535;
			static const int	D3D12_CS_TGSM_REGISTER_COUNT	= 8192;
			static const int	D3D12_CS_TGSM_REGISTER_READS_PER_INST	= 1;
			static const int	D3D12_CS_TGSM_RESOURCE_REGISTER_COMPONENTS	= 1;
			static const int	D3D12_CS_TGSM_RESOURCE_REGISTER_READ_PORTS	= 1;
			static const int	D3D12_CS_THREADGROUPID_REGISTER_COMPONENTS	= 3;
			static const int	D3D12_CS_THREADGROUPID_REGISTER_COUNT	= 1;
			static const int	D3D12_CS_THREADIDINGROUPFLATTENED_REGISTER_COMPONENTS	= 1;
			static const int	D3D12_CS_THREADIDINGROUPFLATTENED_REGISTER_COUNT	= 1;
			static const int	D3D12_CS_THREADIDINGROUP_REGISTER_COMPONENTS	= 3;
			static const int	D3D12_CS_THREADIDINGROUP_REGISTER_COUNT	= 1;
			static const int	D3D12_CS_THREADID_REGISTER_COMPONENTS	= 3;
			static const int	D3D12_CS_THREADID_REGISTER_COUNT	= 1;
			static const int	D3D12_CS_THREAD_GROUP_MAX_THREADS_PER_GROUP	= 1024;
			static const int	D3D12_CS_THREAD_GROUP_MAX_X	= 1024;
			static const int	D3D12_CS_THREAD_GROUP_MAX_Y	= 1024;
			static const int	D3D12_CS_THREAD_GROUP_MAX_Z	= 64;
			static const int	D3D12_CS_THREAD_GROUP_MIN_X	= 1;
			static const int	D3D12_CS_THREAD_GROUP_MIN_Y	= 1;
			static const int	D3D12_CS_THREAD_GROUP_MIN_Z	= 1;
			static const int	D3D12_CS_THREAD_LOCAL_TEMP_REGISTER_POOL	= 16384;
			static const float D3D12_DEFAULT_BLEND_FACTOR_ALPHA	= 1.0f;
			static const float D3D12_DEFAULT_BLEND_FACTOR_BLUE	= 1.0f;
			static const float D3D12_DEFAULT_BLEND_FACTOR_GREEN	= 1.0f;
			static const float D3D12_DEFAULT_BLEND_FACTOR_RED	= 1.0f;
			static const float D3D12_DEFAULT_BORDER_COLOR_COMPONENT	= 0.0f;
			static const int	D3D12_DEFAULT_DEPTH_BIAS	= 0;
			static const float D3D12_DEFAULT_DEPTH_BIAS_CLAMP	= 0.0f;
			static const int	D3D12_DEFAULT_MAX_ANISOTROPY	= 16;
			static const float D3D12_DEFAULT_MIP_LOD_BIAS	= 0.0f;
			static const int	D3D12_DEFAULT_MSAA_RESOURCE_PLACEMENT_ALIGNMENT	= 4194304;
			static const int	D3D12_DEFAULT_RENDER_TARGET_ARRAY_INDEX	= 0;
			static const int	D3D12_DEFAULT_RESOURCE_PLACEMENT_ALIGNMENT	= 65536;
			static const unsigned int	D3D12_DEFAULT_SAMPLE_MASK	= 0xffffffff;
			static const int	D3D12_DEFAULT_SCISSOR_ENDX	= 0;
			static const int	D3D12_DEFAULT_SCISSOR_ENDY	= 0;
			static const int	D3D12_DEFAULT_SCISSOR_STARTX	= 0;
			static const int	D3D12_DEFAULT_SCISSOR_STARTY	= 0;
			static const float D3D12_DEFAULT_SLOPE_SCALED_DEPTH_BIAS	= 0.0f;
			static const int	D3D12_DEFAULT_STENCIL_READ_MASK	= 0xff;
			static const int	D3D12_DEFAULT_STENCIL_REFERENCE	= 0;
			static const int	D3D12_DEFAULT_STENCIL_WRITE_MASK	= 0xff;
			static const int	D3D12_DEFAULT_VIEWPORT_AND_SCISSORRECT_INDEX	= 0;
			static const int	D3D12_DEFAULT_VIEWPORT_HEIGHT	= 0;
			static const float D3D12_DEFAULT_VIEWPORT_MAX_DEPTH	= 0.0f;
			static const float D3D12_DEFAULT_VIEWPORT_MIN_DEPTH	= 0.0f;
			static const int	D3D12_DEFAULT_VIEWPORT_TOPLEFTX	= 0;
			static const int	D3D12_DEFAULT_VIEWPORT_TOPLEFTY	= 0;
			static const int	D3D12_DEFAULT_VIEWPORT_WIDTH	= 0;
			static const unsigned int	D3D12_DESCRIPTOR_RANGE_OFFSET_APPEND	= 0xffffffff;
			static const unsigned int	D3D12_DRIVER_RESERVED_REGISTER_SPACE_VALUES_END	= 0xfffffff7;
			static const unsigned int	D3D12_DRIVER_RESERVED_REGISTER_SPACE_VALUES_START	= 0xfffffff0;
			static const int	D3D12_DS_INPUT_CONTROL_POINTS_MAX_TOTAL_SCALARS	= 3968;
			static const int	D3D12_DS_INPUT_CONTROL_POINT_REGISTER_COMPONENTS	= 4;
			static const int	D3D12_DS_INPUT_CONTROL_POINT_REGISTER_COMPONENT_BIT_COUNT	= 32;
			static const int	D3D12_DS_INPUT_CONTROL_POINT_REGISTER_COUNT	= 32;
			static const int	D3D12_DS_INPUT_CONTROL_POINT_REGISTER_READS_PER_INST	= 2;
			static const int	D3D12_DS_INPUT_CONTROL_POINT_REGISTER_READ_PORTS	= 1;
			static const int	D3D12_DS_INPUT_DOMAIN_POINT_REGISTER_COMPONENTS	= 3;
			static const int	D3D12_DS_INPUT_DOMAIN_POINT_REGISTER_COMPONENT_BIT_COUNT	= 32;
			static const int	D3D12_DS_INPUT_DOMAIN_POINT_REGISTER_COUNT	= 1;
			static const int	D3D12_DS_INPUT_DOMAIN_POINT_REGISTER_READS_PER_INST	= 2;
			static const int	D3D12_DS_INPUT_DOMAIN_POINT_REGISTER_READ_PORTS	= 1;
			static const int	D3D12_DS_INPUT_PATCH_CONSTANT_REGISTER_COMPONENTS	= 4;
			static const int	D3D12_DS_INPUT_PATCH_CONSTANT_REGISTER_COMPONENT_BIT_COUNT	= 32;
			static const int	D3D12_DS_INPUT_PATCH_CONSTANT_REGISTER_COUNT	= 32;
			static const int	D3D12_DS_INPUT_PATCH_CONSTANT_REGISTER_READS_PER_INST	= 2;
			static const int	D3D12_DS_INPUT_PATCH_CONSTANT_REGISTER_READ_PORTS	= 1;
			static const int	D3D12_DS_INPUT_PRIMITIVE_ID_REGISTER_COMPONENTS	= 1;
			static const int	D3D12_DS_INPUT_PRIMITIVE_ID_REGISTER_COMPONENT_BIT_COUNT	= 32;
			static const int	D3D12_DS_INPUT_PRIMITIVE_ID_REGISTER_COUNT	= 1;
			static const int	D3D12_DS_INPUT_PRIMITIVE_ID_REGISTER_READS_PER_INST	= 2;
			static const int	D3D12_DS_INPUT_PRIMITIVE_ID_REGISTER_READ_PORTS	= 1;
			static const int	D3D12_DS_OUTPUT_REGISTER_COMPONENTS	= 4;
			static const int	D3D12_DS_OUTPUT_REGISTER_COMPONENT_BIT_COUNT	= 32;
			static const int	D3D12_DS_OUTPUT_REGISTER_COUNT	= 32;
			static const int D3D12_FLOAT16_FUSED_TOLERANCE_IN_ULP	= 0.6;
			static const float D3D12_FLOAT32_MAX	= 3.402823466e+38f;
			static const float D3D12_FLOAT32_TO_INTEGER_TOLERANCE_IN_ULP	= 0.6f;
			static const float D3D12_FLOAT_TO_SRGB_EXPONENT_DENOMINATOR	= 2.4f;
			static const float D3D12_FLOAT_TO_SRGB_EXPONENT_NUMERATOR	= 1.0f;
			static const float D3D12_FLOAT_TO_SRGB_OFFSET	= 0.055f;
			static const float D3D12_FLOAT_TO_SRGB_SCALE_1	= 12.92f;
			static const float D3D12_FLOAT_TO_SRGB_SCALE_2	= 1.055f;
			static const float D3D12_FLOAT_TO_SRGB_THRESHOLD	= 0.0031308f;
			static const float D3D12_FTOI_INSTRUCTION_MAX_INPUT	= 2147483647.999f;
			static const float D3D12_FTOI_INSTRUCTION_MIN_INPUT	= -2147483648.999f;
			static const float D3D12_FTOU_INSTRUCTION_MAX_INPUT	= 4294967295.999f;
			static const float D3D12_FTOU_INSTRUCTION_MIN_INPUT	= 0.0f;
			static const int	D3D12_GS_INPUT_INSTANCE_ID_READS_PER_INST	= 2;
			static const int	D3D12_GS_INPUT_INSTANCE_ID_READ_PORTS	= 1;
			static const int	D3D12_GS_INPUT_INSTANCE_ID_REGISTER_COMPONENTS	= 1;
			static const int	D3D12_GS_INPUT_INSTANCE_ID_REGISTER_COMPONENT_BIT_COUNT	= 32;
			static const int	D3D12_GS_INPUT_INSTANCE_ID_REGISTER_COUNT	= 1;
			static const int	D3D12_GS_INPUT_PRIM_CONST_REGISTER_COMPONENTS	= 1;
			static const int	D3D12_GS_INPUT_PRIM_CONST_REGISTER_COMPONENT_BIT_COUNT	= 32;
			static const int	D3D12_GS_INPUT_PRIM_CONST_REGISTER_COUNT	= 1;
			static const int	D3D12_GS_INPUT_PRIM_CONST_REGISTER_READS_PER_INST	= 2;
			static const int	D3D12_GS_INPUT_PRIM_CONST_REGISTER_READ_PORTS	= 1;
			static const int	D3D12_GS_INPUT_REGISTER_COMPONENTS	= 4;
			static const int	D3D12_GS_INPUT_REGISTER_COMPONENT_BIT_COUNT	= 32;
			static const int	D3D12_GS_INPUT_REGISTER_COUNT	= 32;
			static const int	D3D12_GS_INPUT_REGISTER_READS_PER_INST	= 2;
			static const int	D3D12_GS_INPUT_REGISTER_READ_PORTS	= 1;
			static const int	D3D12_GS_INPUT_REGISTER_VERTICES	= 32;
			static const int	D3D12_GS_MAX_INSTANCE_COUNT	= 32;
			static const int	D3D12_GS_MAX_OUTPUT_VERTEX_COUNT_ACROSS_INSTANCES	= 1024;
			static const int	D3D12_GS_OUTPUT_ELEMENTS	= 32;
			static const int	D3D12_GS_OUTPUT_REGISTER_COMPONENTS	= 4;
			static const int	D3D12_GS_OUTPUT_REGISTER_COMPONENT_BIT_COUNT	= 32;
			static const int	D3D12_GS_OUTPUT_REGISTER_COUNT	= 32;
			static const int	D3D12_HS_CONTROL_POINT_PHASE_INPUT_REGISTER_COUNT	= 32;
			static const int	D3D12_HS_CONTROL_POINT_PHASE_OUTPUT_REGISTER_COUNT	= 32;
			static const int	D3D12_HS_CONTROL_POINT_REGISTER_COMPONENTS	= 4;
			static const int	D3D12_HS_CONTROL_POINT_REGISTER_COMPONENT_BIT_COUNT	= 32;
			static const int	D3D12_HS_CONTROL_POINT_REGISTER_READS_PER_INST	= 2;
			static const int	D3D12_HS_CONTROL_POINT_REGISTER_READ_PORTS	= 1;
			static const unsigned int	D3D12_HS_FORK_PHASE_INSTANCE_COUNT_UPPER_BOUND	= 0xffffffff;
			static const int	D3D12_HS_INPUT_FORK_INSTANCE_ID_REGISTER_COMPONENTS	= 1;
			static const int	D3D12_HS_INPUT_FORK_INSTANCE_ID_REGISTER_COMPONENT_BIT_COUNT	= 32;
			static const int	D3D12_HS_INPUT_FORK_INSTANCE_ID_REGISTER_COUNT	= 1;
			static const int	D3D12_HS_INPUT_FORK_INSTANCE_ID_REGISTER_READS_PER_INST	= 2;
			static const int	D3D12_HS_INPUT_FORK_INSTANCE_ID_REGISTER_READ_PORTS	= 1;
			static const int	D3D12_HS_INPUT_JOIN_INSTANCE_ID_REGISTER_COMPONENTS	= 1;
			static const int	D3D12_HS_INPUT_JOIN_INSTANCE_ID_REGISTER_COMPONENT_BIT_COUNT	= 32;
			static const int	D3D12_HS_INPUT_JOIN_INSTANCE_ID_REGISTER_COUNT	= 1;
			static const int	D3D12_HS_INPUT_JOIN_INSTANCE_ID_REGISTER_READS_PER_INST	= 2;
			static const int	D3D12_HS_INPUT_JOIN_INSTANCE_ID_REGISTER_READ_PORTS	= 1;
			static const int	D3D12_HS_INPUT_PRIMITIVE_ID_REGISTER_COMPONENTS	= 1;
			static const int	D3D12_HS_INPUT_PRIMITIVE_ID_REGISTER_COMPONENT_BIT_COUNT	= 32;
			static const int	D3D12_HS_INPUT_PRIMITIVE_ID_REGISTER_COUNT	= 1;
			static const int	D3D12_HS_INPUT_PRIMITIVE_ID_REGISTER_READS_PER_INST	= 2;
			static const int	D3D12_HS_INPUT_PRIMITIVE_ID_REGISTER_READ_PORTS	= 1;
			static const unsigned int	D3D12_HS_JOIN_PHASE_INSTANCE_COUNT_UPPER_BOUND	= 0xffffffff;
			static const float D3D12_HS_MAXTESSFACTOR_LOWER_BOUND	= 1.0f;
			static const float D3D12_HS_MAXTESSFACTOR_UPPER_BOUND	= 64.0f;
			static const int	D3D12_HS_OUTPUT_CONTROL_POINTS_MAX_TOTAL_SCALARS	= 3968;
			static const int	D3D12_HS_OUTPUT_CONTROL_POINT_ID_REGISTER_COMPONENTS	= 1;
			static const int	D3D12_HS_OUTPUT_CONTROL_POINT_ID_REGISTER_COMPONENT_BIT_COUNT	= 32;
			static const int	D3D12_HS_OUTPUT_CONTROL_POINT_ID_REGISTER_COUNT	= 1;
			static const int	D3D12_HS_OUTPUT_CONTROL_POINT_ID_REGISTER_READS_PER_INST	= 2;
			static const int	D3D12_HS_OUTPUT_CONTROL_POINT_ID_REGISTER_READ_PORTS	= 1;
			static const int	D3D12_HS_OUTPUT_PATCH_CONSTANT_REGISTER_COMPONENTS	= 4;
			static const int	D3D12_HS_OUTPUT_PATCH_CONSTANT_REGISTER_COMPONENT_BIT_COUNT	= 32;
			static const int	D3D12_HS_OUTPUT_PATCH_CONSTANT_REGISTER_COUNT	= 32;
			static const int	D3D12_HS_OUTPUT_PATCH_CONSTANT_REGISTER_READS_PER_INST	= 2;
			static const int	D3D12_HS_OUTPUT_PATCH_CONSTANT_REGISTER_READ_PORTS	= 1;
			static const int	D3D12_HS_OUTPUT_PATCH_CONSTANT_REGISTER_SCALAR_COMPONENTS	= 128;
			static const int	D3D12_IA_DEFAULT_INDEX_BUFFER_OFFSET_IN_BYTES	= 0;
			static const int	D3D12_IA_DEFAULT_PRIMITIVE_TOPOLOGY	= 0;
			static const int	D3D12_IA_DEFAULT_VERTEX_BUFFER_OFFSET_IN_BYTES	= 0;
			static const int	D3D12_IA_INDEX_INPUT_RESOURCE_SLOT_COUNT	= 1;
			static const int	D3D12_IA_INSTANCE_ID_BIT_COUNT	= 32;
			static const int	D3D12_IA_INTEGER_ARITHMETIC_BIT_COUNT	= 32;
			static const int	D3D12_IA_PATCH_MAX_CONTROL_POINT_COUNT	= 32;
			static const int	D3D12_IA_PRIMITIVE_ID_BIT_COUNT	= 32;
			static const int	D3D12_IA_VERTEX_ID_BIT_COUNT	= 32;
			static const int	D3D12_IA_VERTEX_INPUT_RESOURCE_SLOT_COUNT	= 32;
			static const int	D3D12_IA_VERTEX_INPUT_STRUCTURE_ELEMENTS_COMPONENTS	= 128;
			static const int	D3D12_IA_VERTEX_INPUT_STRUCTURE_ELEMENT_COUNT	= 32;
			static const unsigned int	D3D12_INTEGER_DIVIDE_BY_ZERO_QUOTIENT	= 0xffffffff;
			static const unsigned int	D3D12_INTEGER_DIVIDE_BY_ZERO_REMAINDER	= 0xffffffff;
			static const unsigned int	D3D12_KEEP_RENDER_TARGETS_AND_DEPTH_STENCIL	= 0xffffffff;
			static const unsigned int	D3D12_KEEP_UNORDERED_ACCESS_VIEWS	= 0xffffffff;
			static const float D3D12_LINEAR_GAMMA	= 1.0f;
			static const int	D3D12_MAJOR_VERSION	= 12;
			static const float D3D12_MAX_BORDER_COLOR_COMPONENT	= 1.0f;
			static const float D3D12_MAX_DEPTH	= 1.0f;
			static const int	D3D12_MAX_LIVE_STATIC_SAMPLERS	= 2032;
			static const int	D3D12_MAX_MAXANISOTROPY	= 16;
			static const int	D3D12_MAX_MULTISAMPLE_SAMPLE_COUNT	= 32;
			static const float D3D12_MAX_POSITION_VALUE	= 3.402823466e+34f;
			static const int	D3D12_MAX_ROOT_COST	= 64;
			static const int	D3D12_MAX_SHADER_VISIBLE_DESCRIPTOR_HEAP_SIZE_TIER_1	= 1000000;
			static const int	D3D12_MAX_SHADER_VISIBLE_DESCRIPTOR_HEAP_SIZE_TIER_2	= 1000000;
			static const int	D3D12_MAX_SHADER_VISIBLE_SAMPLER_HEAP_SIZE	= 2048;
			static const int	D3D12_MAX_TEXTURE_DIMENSION_2_TO_EXP	= 17;
			static const int	D3D12_MAX_VIEW_INSTANCE_COUNT	= 4;
			static const int	D3D12_MINOR_VERSION	= 0;
			static const float D3D12_MIN_BORDER_COLOR_COMPONENT	= 0.0f;
			static const float D3D12_MIN_DEPTH	= 0.0f;
			static const int	D3D12_MIN_MAXANISOTROPY	= 0;
			static const float D3D12_MIP_LOD_BIAS_MAX	= 15.99f;
			static const float D3D12_MIP_LOD_BIAS_MIN	= -16.0f;
			static const int	D3D12_MIP_LOD_FRACTIONAL_BIT_COUNT	= 8;
			static const int	D3D12_MIP_LOD_RANGE_BIT_COUNT	= 8;
			static const float D3D12_MULTISAMPLE_ANTIALIAS_LINE_WIDTH	= 1.4f;
			static const int	D3D12_NONSAMPLE_FETCH_OUT_OF_RANGE_ACCESS_RESULT	= 0;
			static const unsigned int	D3D12_OS_RESERVED_REGISTER_SPACE_VALUES_END	= 0xffffffff;
			static const unsigned int	D3D12_OS_RESERVED_REGISTER_SPACE_VALUES_START	= 0xfffffff8;
			static const unsigned int	D3D12_PACKED_TILE	= 0xffffffff;
			static const int	D3D12_PIXEL_ADDRESS_RANGE_BIT_COUNT	= 15;
			static const int	D3D12_PRE_SCISSOR_PIXEL_ADDRESS_RANGE_BIT_COUNT	= 16;
			static const int	D3D12_PS_CS_UAV_REGISTER_COMPONENTS	= 1;
			static const int	D3D12_PS_CS_UAV_REGISTER_COUNT	= 8;
			static const int	D3D12_PS_CS_UAV_REGISTER_READS_PER_INST	= 1;
			static const int	D3D12_PS_CS_UAV_REGISTER_READ_PORTS	= 1;
			static const unsigned int	D3D12_PS_FRONTFACING_DEFAULT_VALUE	= 0xffffffff;
			static const int	D3D12_PS_FRONTFACING_FALSE_VALUE	= 0;
			static const unsigned int	D3D12_PS_FRONTFACING_TRUE_VALUE	= 0xffffffff;
			static const int	D3D12_PS_INPUT_REGISTER_COMPONENTS	= 4;
			static const int	D3D12_PS_INPUT_REGISTER_COMPONENT_BIT_COUNT	= 32;
			static const int	D3D12_PS_INPUT_REGISTER_COUNT	= 32;
			static const int	D3D12_PS_INPUT_REGISTER_READS_PER_INST	= 2;
			static const int	D3D12_PS_INPUT_REGISTER_READ_PORTS	= 1;
			static const float D3D12_PS_LEGACY_PIXEL_CENTER_FRACTIONAL_COMPONENT	= 0.0f;
			static const int	D3D12_PS_OUTPUT_DEPTH_REGISTER_COMPONENTS	= 1;
			static const int	D3D12_PS_OUTPUT_DEPTH_REGISTER_COMPONENT_BIT_COUNT	= 32;
			static const int	D3D12_PS_OUTPUT_DEPTH_REGISTER_COUNT	= 1;
			static const int	D3D12_PS_OUTPUT_MASK_REGISTER_COMPONENTS	= 1;
			static const int	D3D12_PS_OUTPUT_MASK_REGISTER_COMPONENT_BIT_COUNT	= 32;
			static const int	D3D12_PS_OUTPUT_MASK_REGISTER_COUNT	= 1;
			static const int	D3D12_PS_OUTPUT_REGISTER_COMPONENTS	= 4;
			static const int	D3D12_PS_OUTPUT_REGISTER_COMPONENT_BIT_COUNT	= 32;
			static const int	D3D12_PS_OUTPUT_REGISTER_COUNT	= 8;
			static const float D3D12_PS_PIXEL_CENTER_FRACTIONAL_COMPONENT	= 0.5f;
			static const int	D3D12_RAW_UAV_SRV_BYTE_ALIGNMENT	= 16;
			static const int	D3D12_RAYTRACING_AABB_BYTE_ALIGNMENT	= 8;
			static const int	D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BYTE_ALIGNMENT	= 256;
			static const int	D3D12_RAYTRACING_INSTANCE_DESCS_BYTE_ALIGNMENT	= 16;
			static const int	D3D12_RAYTRACING_MAX_ATTRIBUTE_SIZE_IN_BYTES	= 32;
			static const int	D3D12_RAYTRACING_MAX_DECLARABLE_TRACE_RECURSION_DEPTH	= 31;
			static const int	D3D12_RAYTRACING_MAX_GEOMETRIES_PER_BOTTOM_LEVEL_ACCELERATION_STRUCTURE	= 16777216;
			static const int	D3D12_RAYTRACING_MAX_INSTANCES_PER_TOP_LEVEL_ACCELERATION_STRUCTURE	= 16777216;
			static const int	D3D12_RAYTRACING_MAX_PRIMITIVES_PER_BOTTOM_LEVEL_ACCELERATION_STRUCTURE	= 536870912;
			static const int	D3D12_RAYTRACING_MAX_RAY_GENERATION_SHADER_THREADS	= 1073741824;
			static const int	D3D12_RAYTRACING_MAX_SHADER_RECORD_STRIDE	= 4096;
			static const int	D3D12_RAYTRACING_SHADER_RECORD_BYTE_ALIGNMENT	= 32;
			static const int	D3D12_RAYTRACING_SHADER_TABLE_BYTE_ALIGNMENT	= 64;
			static const int	D3D12_RAYTRACING_TRANSFORM3X4_BYTE_ALIGNMENT	= 16;
			static const int	D3D12_REQ_BLEND_OBJECT_COUNT_PER_DEVICE	= 4096;
			static const int	D3D12_REQ_BUFFER_RESOURCE_TEXEL_COUNT_2_TO_EXP	= 27;
			static const int	D3D12_REQ_CONSTANT_BUFFER_ELEMENT_COUNT	= 4096;
			static const int	D3D12_REQ_DEPTH_STENCIL_OBJECT_COUNT_PER_DEVICE	= 4096;
			static const int	D3D12_REQ_DRAWINDEXED_INDEX_COUNT_2_TO_EXP	= 32;
			static const int	D3D12_REQ_DRAW_VERTEX_COUNT_2_TO_EXP	= 32;
			static const int	D3D12_REQ_FILTERING_HW_ADDRESSABLE_RESOURCE_DIMENSION	= 16384;
			static const int	D3D12_REQ_GS_INVOCATION_32BIT_OUTPUT_COMPONENT_LIMIT	= 1024;
			static const int	D3D12_REQ_IMMEDIATE_CONSTANT_BUFFER_ELEMENT_COUNT	= 4096;
			static const int	D3D12_REQ_MAXANISOTROPY	= 16;
			static const int	D3D12_REQ_MIP_LEVELS	= 15;
			static const int	D3D12_REQ_MULTI_ELEMENT_STRUCTURE_SIZE_IN_BYTES	= 2048;
			static const int	D3D12_REQ_RASTERIZER_OBJECT_COUNT_PER_DEVICE	= 4096;
			static const int	D3D12_REQ_RENDER_TO_BUFFER_WINDOW_WIDTH	= 16384;
			static const int	D3D12_REQ_RESOURCE_SIZE_IN_MEGABYTES_EXPRESSION_A_TERM	= 128;
			static const float D3D12_REQ_RESOURCE_SIZE_IN_MEGABYTES_EXPRESSION_B_TERM	= 0.25f;
			static const int	D3D12_REQ_RESOURCE_SIZE_IN_MEGABYTES_EXPRESSION_C_TERM	= 2048;
			static const int	D3D12_REQ_RESOURCE_VIEW_COUNT_PER_DEVICE_2_TO_EXP	= 20;
			static const int	D3D12_REQ_SAMPLER_OBJECT_COUNT_PER_DEVICE	= 4096;
			static const int	D3D12_REQ_SUBRESOURCES	= 30720;
			static const int	D3D12_REQ_TEXTURE1D_ARRAY_AXIS_DIMENSION	= 2048;
			static const int	D3D12_REQ_TEXTURE1D_U_DIMENSION	= 16384;
			static const int	D3D12_REQ_TEXTURE2D_ARRAY_AXIS_DIMENSION	= 2048;
			static const int	D3D12_REQ_TEXTURE2D_U_OR_V_DIMENSION	= 16384;
			static const int	D3D12_REQ_TEXTURE3D_U_V_OR_W_DIMENSION	= 2048;
			static const int	D3D12_REQ_TEXTURECUBE_DIMENSION	= 16384;
			static const int	D3D12_RESINFO_INSTRUCTION_MISSING_COMPONENT_RETVAL	= 0;
			static const unsigned int	D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES	= 0xffffffff;
			static const int	D3D12_RS_SET_SHADING_RATE_COMBINER_COUNT	= 2;
			static const int	D3D12_SHADER_IDENTIFIER_SIZE_IN_BYTES	= 32;
			static const int	D3D12_SHADER_MAJOR_VERSION	= 5;
			static const int	D3D12_SHADER_MAX_INSTANCES	= 65535;
			static const int	D3D12_SHADER_MAX_INTERFACES	= 253;
			static const int	D3D12_SHADER_MAX_INTERFACE_CALL_SITES	= 4096;
			static const int	D3D12_SHADER_MAX_TYPES	= 65535;
			static const int	D3D12_SHADER_MINOR_VERSION	= 1;
			static const int	D3D12_SHIFT_INSTRUCTION_PAD_VALUE	= 0;
			static const int	D3D12_SHIFT_INSTRUCTION_SHIFT_VALUE_BIT_COUNT	= 5;
			static const int	D3D12_SIMULTANEOUS_RENDER_TARGET_COUNT	= 8;
			static const int	D3D12_SMALL_MSAA_RESOURCE_PLACEMENT_ALIGNMENT	= 65536;
			static const int	D3D12_SMALL_RESOURCE_PLACEMENT_ALIGNMENT	= 4096;
			static const int	D3D12_SO_BUFFER_MAX_STRIDE_IN_BYTES	= 2048;
			static const int	D3D12_SO_BUFFER_MAX_WRITE_WINDOW_IN_BYTES	= 512;
			static const int	D3D12_SO_BUFFER_SLOT_COUNT	= 4;
			static const unsigned int	D3D12_SO_DDI_REGISTER_INDEX_DENOTING_GAP	= 0xffffffff;
			static const unsigned int	D3D12_SO_NO_RASTERIZED_STREAM	= 0xffffffff;
			static const int	D3D12_SO_OUTPUT_COMPONENT_COUNT	= 128;
			static const int	D3D12_SO_STREAM_COUNT	= 4;
			static const int	D3D12_SPEC_DATE_DAY	= 14;
			static const int	D3D12_SPEC_DATE_MONTH	= 11;
			static const int	D3D12_SPEC_DATE_YEAR	= 2014;
			static const float D3D12_SPEC_VERSION	= 1.16;
			static const float D3D12_SRGB_GAMMA	= 2.2f;
			static const float D3D12_SRGB_TO_FLOAT_DENOMINATOR_1	= 12.92f;
			static const float D3D12_SRGB_TO_FLOAT_DENOMINATOR_2	= 1.055f;
			static const float D3D12_SRGB_TO_FLOAT_EXPONENT	= 2.4f;
			static const float D3D12_SRGB_TO_FLOAT_OFFSET	= 0.055f;
			static const float D3D12_SRGB_TO_FLOAT_THRESHOLD	= 0.04045f;
			static const float D3D12_SRGB_TO_FLOAT_TOLERANCE_IN_ULP	= 0.5f;
			static const int	D3D12_STANDARD_COMPONENT_BIT_COUNT	= 32;
			static const int	D3D12_STANDARD_COMPONENT_BIT_COUNT_DOUBLED	= 64;
			static const int	D3D12_STANDARD_MAXIMUM_ELEMENT_ALIGNMENT_BYTE_MULTIPLE	= 4;
			static const int	D3D12_STANDARD_PIXEL_COMPONENT_COUNT	= 128;
			static const int	D3D12_STANDARD_PIXEL_ELEMENT_COUNT	= 32;
			static const int	D3D12_STANDARD_VECTOR_SIZE	= 4;
			static const int	D3D12_STANDARD_VERTEX_ELEMENT_COUNT	= 32;
			static const int	D3D12_STANDARD_VERTEX_TOTAL_COMPONENT_COUNT	= 64;
			static const int	D3D12_SUBPIXEL_FRACTIONAL_BIT_COUNT	= 8;
			static const int	D3D12_SUBTEXEL_FRACTIONAL_BIT_COUNT	= 8;
			static const unsigned int	D3D12_SYSTEM_RESERVED_REGISTER_SPACE_VALUES_END	= 0xffffffff;
			static const unsigned int	D3D12_SYSTEM_RESERVED_REGISTER_SPACE_VALUES_START	= 0xfffffff0;
			static const int	D3D12_TESSELLATOR_MAX_EVEN_TESSELLATION_FACTOR	= 64;
			static const int	D3D12_TESSELLATOR_MAX_ISOLINE_DENSITY_TESSELLATION_FACTOR	= 64;
			static const int	D3D12_TESSELLATOR_MAX_ODD_TESSELLATION_FACTOR	= 63;
			static const int	D3D12_TESSELLATOR_MAX_TESSELLATION_FACTOR	= 64;
			static const int	D3D12_TESSELLATOR_MIN_EVEN_TESSELLATION_FACTOR	= 2;
			static const int	D3D12_TESSELLATOR_MIN_ISOLINE_DENSITY_TESSELLATION_FACTOR	= 1;
			static const int	D3D12_TESSELLATOR_MIN_ODD_TESSELLATION_FACTOR	= 1;
			static const int	D3D12_TEXEL_ADDRESS_RANGE_BIT_COUNT	= 16;
			static const int	D3D12_TEXTURE_DATA_PITCH_ALIGNMENT	= 256;
			static const int	D3D12_TEXTURE_DATA_PLACEMENT_ALIGNMENT	= 512;
			static const int	D3D12_TILED_RESOURCE_TILE_SIZE_IN_BYTES	= 65536;
			static const int	D3D12_TRACKED_WORKLOAD_MAX_INSTANCES	= 32;
			static const int	D3D12_UAV_COUNTER_PLACEMENT_ALIGNMENT	= 4096;
			static const int	D3D12_UAV_SLOT_COUNT	= 64;
			static const int	D3D12_UNBOUND_MEMORY_ACCESS_RESULT	= 0;
			static const int	D3D12_VIDEO_DECODE_MAX_ARGUMENTS	= 10;
			static const int	D3D12_VIDEO_DECODE_MAX_HISTOGRAM_COMPONENTS	= 4;
			static const int	D3D12_VIDEO_DECODE_MIN_BITSTREAM_OFFSET_ALIGNMENT	= 256;
			static const int	D3D12_VIDEO_DECODE_MIN_HISTOGRAM_OFFSET_ALIGNMENT	= 256;
			static const unsigned int	D3D12_VIDEO_DECODE_STATUS_MACROBLOCKS_AFFECTED_UNKNOWN	= 0xffffffff;
			static const int	D3D12_VIDEO_PROCESS_MAX_FILTERS	= 32;
			static const int	D3D12_VIDEO_PROCESS_STEREO_VIEWS	= 2;
			static const int	D3D12_VIEWPORT_AND_SCISSORRECT_MAX_INDEX	= 15;
			static const int	D3D12_VIEWPORT_AND_SCISSORRECT_OBJECT_COUNT_PER_PIPELINE	= 16;
			static const int	D3D12_VIEWPORT_BOUNDS_MAX	= 32767;
			static const int	D3D12_VIEWPORT_BOUNDS_MIN	= -32768;
			static const int	D3D12_VS_INPUT_REGISTER_COMPONENTS	= 4;
			static const int	D3D12_VS_INPUT_REGISTER_COMPONENT_BIT_COUNT	= 32;
			static const int	D3D12_VS_INPUT_REGISTER_COUNT	= 32;
			static const int	D3D12_VS_INPUT_REGISTER_READS_PER_INST	= 2;
			static const int	D3D12_VS_INPUT_REGISTER_READ_PORTS	= 1;
			static const int	D3D12_VS_OUTPUT_REGISTER_COMPONENTS	= 4;
			static const int	D3D12_VS_OUTPUT_REGISTER_COMPONENT_BIT_COUNT	= 32;
			static const int	D3D12_VS_OUTPUT_REGISTER_COUNT	= 32;
			static const int	D3D12_WHQL_CONTEXT_COUNT_FOR_RESOURCE_LIMIT	= 10;
			static const int	D3D12_WHQL_DRAWINDEXED_INDEX_COUNT_2_TO_EXP	= 25;
			static const int	D3D12_WHQL_DRAW_VERTEX_COUNT_2_TO_EXP	= 25;
		};
	}
}
